// ===== MOVIEHUB DATABASE =====
// Replace posterColor with actual image URLs if you have them
// e.g. poster: 'images/avengers.jpg'

// ===== HERO CAROUSEL CONFIG =====
// Each entry: title shown on hero, video background path, and optional poster image path
const HERO_SLIDES = [
  { title: "Iron Man",             video: "videos/hero1.mp4"},
  { title: "Avatar: Fire and Ash", video: "videos/hero2.mp4" },
  { title: "Spider-Man",    video: "videos/hero3.mp4"},
  { title: "Fast And Furious",            video: "videos/hero4.mp4"},
];

const MOVIES = [
  // Action / Trending
  { id:1,  title:"The Boys",                  year:2019, rating:8.4, type:"TV Series", genres:["Action","Drama","Sci-Fi"],        quality:"HD",  description:"A group of vigilantes known as 'The Boys' set out to take down corrupt superheroes who abuse their powers. A dark satire of superhero culture.",                     cast:["Karl Urban","Jack Quaid","Antony Starr"],              director:"Eric Kripke",          duration:"60 min/ep", poster:"images/posters/the_boys.jpg",                  posterColor:"#1a0a2e", trailer:"videos/trailers/the_boys_trailer.mp4",                  trending:true },
  { id:2,  title:"The Super Mario Bros. Movie",year:2026, rating:6.9, type:"Movie",     genres:["Animation","Adventure","Comedy"], quality:"CAM", description:"Mario and his brother Luigi are transported to the Mushroom Kingdom where they must save Princess Peach from the clutches of Bowser.",                           cast:["Chris Pratt","Anya Taylor-Joy","Jack Black"],          director:"Aaron Horvath",        duration:"92 min",    poster:"images/posters/super_mario.jpg",               posterColor:"#1a1a0a", trailer:"videos/trailers/super_mario_trailer.mp4",               trending:true },
  { id:3,  title:"Thrash",                     year:2026, rating:6.1, type:"Movie",     genres:["Action","Thriller"],              quality:"CAM", description:"A gritty underground street racing thriller set across the neon-lit streets of a dystopian city.",                                                           cast:["John Boyega","Zendaya","Oscar Isaac"],                 director:"Chad Stahelski",       duration:"110 min",   poster:"images/posters/thrash.jpg",                    posterColor:"#1a0000", trailer:"videos/trailers/thrash_trailer.mp4",                    trending:true },
  { id:4,  title:"Avatar: Fire and Ash",        year:2025, rating:7.4, type:"Movie",     genres:["Action","Adventure","Sci-Fi"],    quality:"HD",  description:"Jake Sully and Neytiri face a new threat from a powerful volcanic clan as they fight to protect Pandora and their family.",                                   cast:["Sam Worthington","Zoe Saldana","Sigourney Weaver"],   director:"James Cameron",        duration:"162 min",   poster:"images/posters/avatar_fire_and_ash.jpg",       posterColor:"#0a1a2a", trailer:"videos/trailers/avatar_fire_and_ash_trailer.mp4",       trending:true },
  { id:5,  title:"Project Hail Mary",           year:2026, rating:8.2, type:"Movie",     genres:["Sci-Fi","Adventure"],             quality:"HD",  description:"A lone astronaut wakes up with no memory to discover he's on a mission to save Earth from an extinction-level threat.",                                     cast:["Ryan Gosling","Zach Galifianakis"],                    director:"Phil Lord",            duration:"140 min",   poster:"images/posters/project_hail_mary.jpg",         posterColor:"#0a0a2a", trailer:"videos/trailers/project_hail_mary_trailer.mp4",         trending:true },
  { id:6,  title:"One Piece",                   year:1999, rating:8.7, type:"TV Series", genres:["Animation","Action","Adventure"], quality:"HD",  description:"Monkey D. Luffy and his pirate crew explore a vast ocean in search of the legendary treasure 'One Piece' to become King of the Pirates.",              cast:["Mayumi Tanaka","Akemi Okamura","Kazuya Nakai"],        director:"Eiichiro Oda",         duration:"24 min/ep", poster:"images/posters/one_piece.jpg",                 posterColor:"#0a1520", trailer:"videos/trailers/one_piece_trailer.mp4",                 trending:true },
  { id:7,  title:"Outcome",                     year:2026, rating:7.2, type:"Movie",     genres:["Drama","Thriller"],               quality:"HD",  description:"A high-stakes political thriller about a disgraced diplomat who uncovers a massive conspiracy that reaches the highest levels of government.",              cast:["Idris Elba","Viola Davis","Michael B. Jordan"],        director:"Ava DuVernay",         duration:"118 min",   poster:"images/posters/outcome.jpg",                   posterColor:"#0f0a00", trailer:"videos/trailers/outcome_trailer.mp4",                   trending:true },
  { id:8,  title:"The Bride!",                  year:2026, rating:6.3, type:"Movie",     genres:["Horror","Romance"],               quality:"CAM", description:"A modern retelling of Bride of Frankenstein, following a young woman who discovers she was created in a laboratory.",                                       cast:["Jessie Buckley","Christian Bale","Penélope Cruz"],     director:"Maggie Gyllenhaal",    duration:"125 min",   poster:"images/posters/the_bride.jpg",                 posterColor:"#1a0a0f", trailer:"videos/trailers/the_bride_trailer.mp4",                 trending:true },

  // Latest Movies
  { id:9,  title:"Malcolm in the Middle",      year:2026, rating:7.8, type:"Movie",     genres:["Comedy","Drama"],                 quality:"HD",  description:"Cult favourite family returns in a long-awaited feature film continuation of the beloved series.",                                                           cast:["Frankie Muniz","Bryan Cranston","Jane Kaczmarek"],     director:"Todd Holland",         duration:"95 min",    poster:"images/posters/malcolm_in_the_middle.jpg",     posterColor:"#1a1a00", trailer:"videos/trailers/malcolm_trailer.mp4" },
  { id:10, title:"Maul: Shadow Lord",          year:2026, rating:7.5, type:"Movie",     genres:["Action","Sci-Fi"],                quality:"HD",  description:"Darth Maul's untold origins are explored in this Star Wars prequel, revealing his path from Dathomir to becoming the Sith Lord's apprentice.",           cast:["Ray Park","Sam Witwer","Katee Sackhoff"],              director:"Dave Filoni",          duration:"135 min",   poster:"images/posters/maul_shadow_lord.jpg",          posterColor:"#1a0000", trailer:"videos/trailers/maul_trailer.mp4" },
  { id:11, title:"Daredevil: Born Again",      year:2026, rating:8.0, type:"TV Series", genres:["Action","Drama","Crime"],         quality:"HD",  description:"Matt Murdock's world is shattered when Kingpin becomes Mayor of New York City, forcing him to don the mask once more.",                                    cast:["Charlie Cox","Vincent D'Onofrio","Deborah Ann Woll"],  director:"Dario Scardapane",     duration:"55 min/ep", poster:"images/posters/daredevil_born_again.jpg",      posterColor:"#1a0000", trailer:"videos/trailers/daredevil_trailer.mp4" },
  { id:12, title:"Bloodhounds",               year:2026, rating:7.6, type:"TV Series", genres:["Action","Crime","Drama"],         quality:"HD",  description:"Two young boxers team up to fight against a violent loan shark organisation in this action-packed Korean thriller.",                                       cast:["Woo Do-hwan","Lee Sang-yi","Heo Jun-ho"],              director:"Jason Kim",            duration:"50 min/ep", poster:"images/posters/bloodhounds.jpg",               posterColor:"#0a0a1a", trailer:"videos/trailers/bloodhounds_trailer.mp4" },
  { id:13, title:"Re:ZERO Season 3",          year:2026, rating:8.3, type:"TV Series", genres:["Animation","Fantasy","Drama"],    quality:"HD",  description:"Subaru continues his journey through the fantasy world of Lugunica, facing even deadlier trials in this long-awaited continuation.",                    cast:["Yusuke Kobayashi","Rie Takahashi","Inori Minase"],     director:"Masaharu Watanabe",    duration:"24 min/ep", poster:"images/posters/rezero_season3.jpg",            posterColor:"#0a1520", trailer:"videos/trailers/rezero_trailer.mp4" },
  { id:14, title:"Frieren: Beyond Journey's End",year:2026,rating:9.0,type:"TV Series",genres:["Animation","Fantasy","Adventure"],quality:"HD",  description:"An elf mage reflects on her life after the defeat of the Demon King, choosing to journey the world to better understand humanity.",                        cast:["Atsumi Tanezaki","Konomi Kohara","Kana Hanazawa"],     director:"Keiichiro Saito",      duration:"24 min/ep", poster:"images/posters/frieren.jpg",                   posterColor:"#1a2a1a", trailer:"videos/trailers/frieren_trailer.mp4" },
  { id:15, title:"Crime 101",                 year:2026, rating:6.8, type:"Movie",     genres:["Crime","Thriller"],               quality:"HD",  description:"A seasoned detective partners with an unlikely ally — a recently released con man — to dismantle an underground criminal empire.",                        cast:["Oscar Isaac","Jamie Foxx","Lupita Nyong'o"],           director:"Antoine Fuqua",        duration:"122 min",   poster:"images/posters/crime_101.jpg",                 posterColor:"#0a0a0a", trailer:"videos/trailers/crime101_trailer.mp4" },
  { id:16, title:"The Drama",                 year:2026, rating:7.1, type:"Movie",     genres:["Drama","Romance"],                quality:"HD",  description:"A raw, intimate portrait of three interconnected relationships navigating love, loss, and the search for meaning in contemporary Seoul.",                cast:["Park Seo-jun","Han So-hee","Lee Jung-eun"],            director:"Park Chan-wook",       duration:"128 min",   poster:"images/posters/the_drama.jpg",                 posterColor:"#1a0a0a", trailer:"videos/trailers/the_drama_trailer.mp4" },
  { id:17, title:"Interstellar",            year:2026, rating:8.5, type:"Movie",     genres:["Sci-Fi","Drama","Adventure"],     quality:"HD",  description:"A new team of astronauts travels beyond known space following transmissions received from Cooper's original mission.",                                    cast:["Timothée Chalamet","Florence Pugh","Matthew McConaughey"],director:"Christopher Nolan",  duration:"168 min",   poster:"images/posters/interstellar.jpg",             posterColor:"#000a1a", trailer:"videos/trailers/interstellar_trailer.mp4" },
  { id:18, title:"Oppenheimer: Legacy",       year:2026, rating:7.9, type:"Movie",     genres:["Drama","History"],               quality:"HD",  description:"A documentary-drama exploring the lasting political and ethical fallout of the Manhattan Project decades after its conclusion.",                         cast:["Cillian Murphy","Emily Blunt"],                        director:"Christopher Nolan",    duration:"110 min",   poster:"images/posters/oppenheimer.jpg",        posterColor:"#1a0f00", trailer:"videos/trailers/oppenheimer_legacy_trailer.mp4" },
  { id:19, title:"Sentimental Value",      year:2026, rating:7.3, type:"TV Series", genres:["Fantasy","Action","Drama"],       quality:"HD",  description:"Geralt of Rivia continues his adventures in the Continent, now with a new face and darker challenges threatening the world's balance.",               cast:["Liam Hemsworth","Freya Allan","Joey Batey"],           director:"Lauren Schmidt Hissrich",duration:"60 min/ep",poster:"images/posters/sentimental_value.jpg",           posterColor:"#0f1a0f", trailer:"videos/trailers/sentimental_value_trailer.mp4" },
  { id:20, title:"Alien: Romulus",          year:2026, rating:7.7, type:"Movie",     genres:["Horror","Sci-Fi","Action"],       quality:"HD",  description:"The crew of a deep-space mining vessel encounter a derelict spacecraft harbouring a terrifying new form of xenomorph.",                               cast:["Cailee Spaeny","Isabela Merced"],                      director:"Fede Álvarez",         duration:"116 min",   poster:"images/posters/alien_romulus.jpg",            posterColor:"#0a0f00", trailer:"videos/trailers/alien_romulus_trailer.mp4" },
  { id:21, title:"Gladiator",             year:2026, rating:7.2, type:"Movie",     genres:["Action","Drama","History"],       quality:"CAM", description:"The son of Maximus fights to dismantle a corrupt Senate that has enslaved the people of Rome in this epic conclusion.",                                   cast:["Paul Mescal","Pedro Pascal","Denzel Washington"],      director:"Ridley Scott",         duration:"148 min",   poster:"images/posters/gladiator.jpg",                posterColor:"#1a0a00", trailer:"videos/trailers/gladiator_trailer.mp4" },
  { id:22, title:"The Last of Us Season 3",  year:2026, rating:9.1, type:"TV Series", genres:["Drama","Horror","Sci-Fi"],        quality:"HD",  description:"Joel and Ellie's story reaches its harrowing conclusion as a final confrontation with the Fireflies shapes the fate of humanity.",                    cast:["Pedro Pascal","Bella Ramsey","Gabriel Luna"],          director:"Craig Mazin",          duration:"65 min/ep", poster:"images/posters/last_of_us.jpg",             posterColor:"#1a1a0a", trailer:"videos/trailers/last_of_us_trailer.mp4" },
  { id:23, title:"Kung Fu Panda 4",           year:2026, rating:7.0, type:"Movie",     genres:["Animation","Comedy","Action"],    quality:"HD",  description:"Po and the Furious Five face their most epic challenge yet when a supernatural villain threatens to erase all memory from the Valley of Peace.",       cast:["Jack Black","Angelina Jolie","Jackie Chan"],           director:"Jennifer Yuh Nelson",  duration:"95 min",    poster:"images/posters/kung_fu_panda_4.jpg",            posterColor:"#0a1a1a", trailer:"videos/trailers/kung_fu_panda4_trailer.mp4" },
  { id:24, title:"Stranger Things Season 5", year:2026, rating:8.8, type:"TV Series", genres:["Horror","Sci-Fi","Drama"],        quality:"HD",  description:"The final battle between the Hawkins gang and Vecna reaches its apocalyptic conclusion in this season finale event.",                                  cast:["Millie Bobby Brown","Finn Wolfhard","Noah Schnapp"],   director:"The Duffer Brothers",  duration:"75 min/ep", poster:"images/posters/stranger_things.jpg",        posterColor:"#0a0a1a", trailer:"videos/trailers/stranger_things_trailer.mp4" },

  // Top IMDB classics
  { id:100,title:"The Shawshank Redemption",  year:1994, rating:9.3, type:"Movie",     genres:["Drama","Crime"],                  quality:"HD",  description:"Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",                                 cast:["Tim Robbins","Morgan Freeman"],                        director:"Frank Darabont",       duration:"142 min",   poster:"images/posters/shawshank.jpg",                 posterColor:"#1a0a00", trailer:"videos/trailers/shawshank_trailer.mp4",                 topImdb:true },
  { id:101,title:"The Godfather",             year:1972, rating:9.2, type:"Movie",     genres:["Crime","Drama"],                  quality:"HD",  description:"The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",                                                              cast:["Marlon Brando","Al Pacino","James Caan"],              director:"Francis Ford Coppola", duration:"175 min",   poster:"images/posters/the_godfather.jpg",                 posterColor:"#0a0000", trailer:"videos/trailers/godfather_trailer.mp4",                 topImdb:true },
  { id:102,title:"The Dark Knight",           year:2008, rating:9.0, type:"Movie",     genres:["Action","Crime","Drama"],         quality:"HD",  description:"When the menace known as the Joker wreaks havoc on Gotham City, Batman must accept one of the greatest psychological tests of his ability to fight injustice.", cast:["Christian Bale","Heath Ledger","Aaron Eckhart"],      director:"Christopher Nolan",    duration:"152 min",   poster:"images/posters/dark_knight.jpg",               posterColor:"#000010", trailer:"videos/trailers/dark_knight_trailer.mp4",               topImdb:true },
  { id:103,title:"Schindler's List",          year:1993, rating:8.9, type:"Movie",     genres:["Drama","History","War"],          quality:"HD",  description:"In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.",                     cast:["Liam Neeson","Ralph Fiennes","Ben Kingsley"],          director:"Steven Spielberg",     duration:"195 min",   poster:"images/posters/schindlers_list.jpg",           posterColor:"#0a0a0a", trailer:"videos/trailers/schindlers_list_trailer.mp4",           topImdb:true },
  { id:104,title:"Pulp Fiction",              year:1994, rating:8.9, type:"Movie",     genres:["Crime","Drama"],                  quality:"HD",  description:"The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",      cast:["John Travolta","Uma Thurman","Samuel L. Jackson"],     director:"Quentin Tarantino",    duration:"154 min",   poster:"images/posters/pulp_fiction.jpg",              posterColor:"#1a0a00", trailer:"videos/trailers/pulp_fiction_trailer.mp4",              topImdb:true },
  { id:105,title:"Forrest Gump",              year:1994, rating:8.8, type:"Movie",     genres:["Drama","Romance"],                quality:"HD",  description:"The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75.", cast:["Tom Hanks","Robin Wright","Gary Sinise"],            director:"Robert Zemeckis",      duration:"142 min",   poster:"images/posters/forrest_gump.jpg",              posterColor:"#0a1a0a", trailer:"videos/trailers/forrest_gump_trailer.mp4",              topImdb:true },
  { id:106,title:"Inception",                 year:2010, rating:8.8, type:"Movie",     genres:["Action","Sci-Fi","Thriller"],     quality:"HD",  description:"A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",        cast:["Leonardo DiCaprio","Joseph Gordon-Levitt","Elliot Page"],director:"Christopher Nolan",  duration:"148 min",   poster:"images/posters/inception.jpg",                 posterColor:"#000a1a", trailer:"videos/trailers/inception_trailer.mp4",                 topImdb:true },
  { id:107,title:"Breaking Bad",              year:2008, rating:9.5, type:"TV Series", genres:["Crime","Drama","Thriller"],       quality:"HD",  description:"A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student.",        cast:["Bryan Cranston","Aaron Paul","Anna Gunn"],             director:"Vince Gilligan",       duration:"47 min/ep", poster:"images/posters/breaking_bad.jpg",              posterColor:"#1a1a00", trailer:"videos/trailers/breaking_bad_trailer.mp4",              topImdb:true },
  { id:108,title:"10 Things I Hate About You",          year:2023, rating:9.3, type:"TV Series", genres:["Documentary"],                    quality:"HD",  description:"David Attenborough narrates this stunning exploration of Earth's most extraordinary habitats and the remarkable animals that call them home.",            cast:["David Attenborough"],                                  director:"Various",              duration:"60 min/ep", poster:"images/posters/10_things_i_hate_about_you.jpg",             posterColor:"#001a0a", trailer:"videos/trailers/10_things_i_hate_about_you_trailer.mp4",             topImdb:true },
];

// ===== TEAM DATA =====
// Edit this array to add yourself and your teammates
const TEAM = [
  {
    name: "Maanas Vishnu ",
    role: "Member 1",
    initials: "M",
    avatarColor: "#1a2e1a",
    photo: "images/maanas.jpeg",           // ← PHOTO PATH (already added)
    portfolio: "https://manacioo.github.io/Maanas_portfolio/",
    github: "https://github.com/Manacioo",
    linkedin: "www.linkedin.com/in/manacioo-vishnu-b51139402"
  },
  {
    name: "Muhammed Sahad",
    role: "Member 2",
    initials: "S",
    avatarColor:"#2e1a1a",
    photo: "images/sahad.jpeg",             // ← ADD YOUR PHOTO: drop the file into the images/ folder and update this filename
    portfolio: "https://sahad-s.github.io/Portfolio-website-/",
    github: "https://github.com/sahad-s",
    linkedin: "https://www.linkedin.com/in/muhammed-sahad-s-b03367334"
  },
  {
    name: "Aswathy B Kumar",
    role: "Member 3",
    initials: "A",
    avatarColor: "#1a1a2e",
    photo: "images/aswathy.jpeg",           // ← ADD YOUR PHOTO: drop the file into the images/ folder and update this filename
    portfolio: "https://babushka-ops.github.io/aswathy_portfolio/",
    github: "https://github.com/babushka-ops",
    linkedin: "https://www.linkedin.com/in/aswathy-b-kumar-109740334"
  },
  {
    name: "Gaadha Jayakumar",
    role: "Member 4",
    initials: "G",
    avatarColor: "#2e1a2a",
    photo: "images/gaadha.jpeg",            // ← ADD YOUR PHOTO: drop the file into the images/ folder and update this filename
    portfolio: "https://gaadha72.github.io/portfolio/",
    github: "https://github.com/gaadha72",
    linkedin: "https://www.linkedin.com/in/gaadha-jayakumar-444738334"
  },
];

const GENRES_MOVIES = ["All","Action","Comedy","Drama","Horror","Sci-Fi","Thriller","Romance","Animation","Crime","Fantasy","Documentary","History","War","Adventure"];
const GENRES_TV = ["All","Action","Drama","Sci-Fi","Horror","Comedy","Crime","Fantasy","Animation","Documentary","Thriller"];
